---
variables:
  TF_MIN_VERSION: "1.3"
  AZURERM_PROVIDER_MIN_VERSION: "3.57"

include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'
  - project: 'rossifumax/projects/cloud/azure/terraform/ci'
    ref: AZ-1290-fix-tf-version
    file: '/pipeline.yml'
...
